[package]
name = "image_text_matcher"
version = "0.0.0"
edition = "2021"

# Using optional dependencies is inconvenient around examples.
# https://github.com/rust-lang/cargo/issues/4663
# We want the examples to 'just work' so we use dev depends there for now.

[profile.dev]
opt-level=3
incremental=true

[dependencies]
serde = {version="1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
imageproc = {version = "0.22.0"}
image = { version = "0.23.6"}
rusttype = { version = "0.9.2"}


[[example]]
name = "dev_image_to_glyph_set"
path = "src/dev_image_to_glyph_set.rs"

[[example]]
name = "dev_glyph_set_print"
path = "src/dev_glyph_set_print.rs"

[[example]]
name = "dev_example_glyphs"
path = "src/dev_example_glyphs.rs"
