[package]
name = "image_text_matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level=3
incremental=true

[dependencies]
imageproc = "0.22.0"
image = { version = "0.23.6"}
rusttype = "0.9.2"

#
serde = {version="1.0", features = ["derive"] }
serde_json = "1.0"

[[example]]
name = "dev_histogram_print"
path = "src/dev_histogram_print.rs"

[[example]]
name = "dev_glyph_set_print"
path = "src/dev_glyph_set_print.rs"
