[package]
name = "image_text_matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level=3
incremental=true

[dependencies]
imageproc = "0.22.0"
image = { version = "0.23.6"}
rusttype = "0.9.2"

