[package]
name = "histogram_text_matcher"
version = "0.0.0"
edition = "2021"
authors = ["Ivor Wanders <ivor@iwanders.net>"]
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level=3
incremental=true

[lib]
# Prevent capturing of benchmark commandline arguments... https://github.com/rust-lang/rust/issues/47241
bench = false

[dependencies]
serde = {version="1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"

imageproc = {version = "0.22.0", optional=true}
image = { version = "0.23.6", optional=true}
rusttype = { version = "0.9.2", optional=true}

[dev-dependencies]
imageproc = {version = "0.22.0"}
image = { version = "0.23.6"}
rusttype = { version = "0.9.2"}
criterion = "0.3"

[features]
image_support = ["imageproc", "image", "rusttype"]

[[example]]
name = "dev_image_to_glyph_set"
path = "examples/dev_image_to_glyph_set.rs"
required-features = ["image_support"]

[[example]]
name = "dev_glyph_set_print"
path = "examples/dev_glyph_set_print.rs"
required-features = ["image_support"]


[[example]]
name = "dev_scan_image"
path = "examples/dev_scan_image.rs"
required-features = ["image_support"]

[[bench]]
name = "bench_scan_image"
harness = false

